app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::get('/', function()
{
	return View::make('index');
});

//ProductController
Route::get('/createProduct', 'ProductController@create');
Route::resource('product','ProductController');
Route::controller('product', 'ProductController');

//UserController
Route::get('user', 'UserController@index');
Route::post('login', array('as'=>'user.login', 'uses'=>'UserController@login'));
Route::post('postAuth', array('as'=>'user.postAuth', 'uses'=>'UserController@postAuth'));
Route::post('register', array('as'=>'user.register', 'uses'=>'UserController@register'));
Route::get('/user/settings', array('as'=>'user.settings', 'uses'=>'UserController@settings'));
Route::get('logout', array('as'=>'user.logout', 'uses'=>'UserController@doLogout'));
Route::resource('user','UserController');
Route::controller('user', 'UserController');


//TestController
Route::get('/test', 'TestController@index');

app/models/User.php
<?php

use Illuminate\Auth\UserTrait;
use Illuminate\Auth\UserInterface;
use Illuminate\Auth\Reminders\RemindableTrait;
use Illuminate\Auth\Reminders\RemindableInterface;
use Zizaco\Entrust\HasRole;

class User extends Eloquent implements UserInterface, RemindableInterface {

	use UserTrait, RemindableTrait, HasRole;

	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'users';

    protected $fillable = array('firstname', 'lastname', 'email', 'password', 'address', 'city', 'phone',
                                'cell_phone', 'status', 'email', 'password');

    public static $registration_rules = [
        'firstname' => 'required',
        'lastname' => 'required',
        'email' => 'required|email|Confirmed',
        'email_confirmation' => 'required|email',
        'password' => 'required|min:8|Confirmed',
        'password_confirmation' => 'required|min:8',
    ];

    public static $login_rules = array(
    'email'    => 'required|email', // make sure the email is an actual email
    'password' => 'required|min:8' // password can only be alphanumeric and has to be greater than 3 characters
    );


    /**
	 * The attributes excluded from the model's JSON form.
	 *
	 * @var array
	 */
	protected $hidden = array('password', 'remember_token');

}

app/controllers/UserController.php
<?php

class UserController extends \BaseController {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		//
//        return "Hello";
		return View::make('users.user_homepage');
	}


	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		//
	}


	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		//
	}


	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		return 'HELLO';
	}


	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		//
	}


	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		//
	}


	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		//
	}


	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function login()
	{
		$input = Input::all();
		return $input;
		return View::make('users.user_dashboard');
		return "Hello";
	}

    //redirect to the login otherwise redirect to register

    public function postAuth(){

        if(Input::get('login')){

            $validator = Validator::make(Input::all(), User::$login_rules);
            // if the validator fails, redirect back to the form
            if ($validator->fails()) {
                return View::make('users.user_homepage')
                    ->withErrors($validator) // send back all errors to the login form
                    ->withInput(Input::except('password')); // send back the input (not the password) so that we can repopulate the form
            }else{
                // create our user data for the authentication
                $user_data = array(
                    'email'     => Input::get('email'),
                    'password'  => Input::get('password')
                );
//                return $user_data['password'];

                if (Auth::attempt($user_data)) {
//                    return Auth::user();
                    //redirect the user to user settings page
                    return View::make('users.user_settings')->with('user_data', Auth::user());

                }else{
                    return View::make('users.user_homepage')->with('login_failed_message', 'Login Failed: User not found');
                }

            }

        }else if(Input::get('register')){
            return View::make('users.user_registration');
        }
    }

//    fetch all the information of user registration
    public function register(){
        $validate = Validator::make(Input::all(), User::$registration_rules);
        if($validate->passes()){
            User::create([
                'firstname'=> Input::get('firstname'),
                'lastname'=>  Input::get('lastname'),
                'email'=>     Input::get('email'),
                'password'=>  Hash::make(Input::get('password')),
                'phone'=>     Input::get('phone'),
                'cell_phone'=>Input::get('cell_phone'),
                'status'=>    0,//Input::has('age') ? intval(Input::get('age')) : null,
            ]);

            return Redirect::to('user')->with('success_message', 'Please wait for the review of your application');
        }else{
            return View::make('users.user_registration')
                ->withErrors($validate->messages())
                ->withInput(Input::except('password', 'password_confirmation'));
        }


    }

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function settings()
	{
		$input = Input::all();
//		return Input::get('email');
		return View::make('users.user_settings');
		return "Hello";
	}


}

app/views/users/user_dashboard.blade.php
/**
* Created by PhpStorm.
* User: MahabubAkram
* Date: 1/18/2015
* Time: 3:47 PM
*/

@extends('layouts.product')
@section('main')


    <div class="col-sm-9 col-md-9 main">
        <!--         <h1 class="page-header">Dashboard</h1>-->
        <div class="row placeholders">
            <div class="col-md-3 panel panel-default">
                <div class="panel-heading" align="center">
                    <h3 class="panel-title">Categories</h3>
                </div>
                <div class="panel-body" align="center">
                    52
                </div>
            </div>
            <div class="col-md-offset-1 col-md-2 panel panel-default">
                <div class="panel-heading" align="center">
                    <h3 class="panel-title">Items</h3>
                </div>
                <div class="panel-body" align="center">
                    20
                </div>
            </div>
            <div class="col-md-offset-1 col-md-2 panel panel-default">
                <div class="panel-heading" align="center">
                    <h3 class="panel-title">Amount</h3>
                </div>
                <div class="panel-body" align="center">
                    20,0000
                </div>
            </div>
            <div class="col-md-offset-1 col-md-2 panel panel-default">
                <div class="panel-heading" align="center">
                    <h3 class="panel-title">Reviews</h3>
                </div>
                <div class="panel-body" align="center">
                    10
                </div>
            </div>
        </div>

        <!--End of panels-->
        <div class="row user-info">
            <h4 style="margin-left: 2%;">Vendor Information</h4>

            <div class="row">
                <div class='form-group' style="clear: both;">
                    <div class="user-key">Name:</div>
                    <div class="user-value">Amarshop</div>
                </div>
                <div class='form-group' style="clear: both;">
                    <div class="user-key">Status:</div>
                    <div class="user-value">Active</div>
                </div>
                <div class='form-group' style="clear: both;">
                    <div class="user-key">Email:</div>
                    <div class="user-value">abd@gmail.com</div>
                </div>
                <div class='form-group' style="clear: both;">
                    <div class="user-key">Phone:</div>
                    <div class="user-value">+880258369:</div>
                </div>
             </div>

            <div class="row">
                <div class='form-group'>
                    <div class="col-md-2" style="float: right; padding-right: 5px; padding-bottom: 5px; margin-right: 5%; margin-bottom: 1%; text-align: center;">
                        <a href="{{action('UserController@settings');}}" class="btn btn-primary bt-lg">Edit</a>
                    </div>
                </div>
            </div>
        </div>


        <!-- End of General Information-->

        <div class="row user-info" style="margin-top: 4em;">
            <h4 style="margin-left: 2%;">Shipping Information</h4>

            <div class="row">
                <div class='form-group' style="clear: both;">
                    <div class="user-key">Address:</div>
                    <div class="user-value">23/1 Mirpur</div>
                </div>
                <div class='form-group' style="clear: both;">
                    <div class="user-key">City:</div>
                    <div class="user-value">Dhaka</div>
                </div>
                <div class='form-group' style="clear: both;">
                    <div class="user-key">Zip Code:</div>
                    <div class="user-value">1207</div>
                </div>
            </div>

            <div class="row">
                <div class='form-group'>
                    <div class="col-md-2 btn btn-primary" style="float: right; padding-right: 5px; padding-bottom: 5px; margin-right: 5%; margin-bottom: 1%; text-align: center;">
                        {{ link_to_route('user.index', 'Edit') }}
                    </div>
                </div>
            </div>
        </div>

    </div>




    <div class="col-sm-3 col-md-3 sidebar">
        <ul class="nav nav-sidebar">
            <li class="active"><a href="#">Overview</a></li>
            <li><a href="#browse"> <span class="glyphicon glyphicon-zoom-in"></span> Browse</a></li>
            <li><a href="#create"> <span class="glyphicon glyphicon-star"></span> Create</a></li>
            <li><a href="#file-convert"> <span class="glyphicon glyphicon-certificate"></span> Match Key</a></li>
            <li><a href="#import"> <span class="glyphicon glyphicon-download-alt"></span> Import token</a></li>
            <li><a href="#feedback"> <span class="glyphicon glyphicon-thumbs-up"></span> Feedback</a></li>
        </ul>

        <ul class="nav nav-sidebar">
            <li><a href="#designer"> <span class="glyphicon glyphicon-user"></span> Designer</a></li>
            <li><a href="#avatar"> <span class="glyphicon glyphicon-user"></span> Avatar</a></li>
            <li><a href="#keyword"> <span class="glyphicon glyphicon-screenshot"></span> Keyword</a></li>
        </ul>
    </div>


@stop

app/views/users/user_homepage.blade.php
/**
 * Created by PhpStorm.
 * User: MahabubAkram
 * Date: 1/18/2015
 * Time: 3:47 PM
 */

@extends('layouts.user')
@section('main')


    <!-- start: Login Form -->
    <div class="row">
        <div class="col-md-6 col-md-offset-1">
            {{ Form::open(array( 'route' =>array('user.postAuth'), 'method' => 'POST')) }}
                <div class="row control-group">

                    <div class="help-block text-danger" >
                        @if(isset($login_failed_message))
                            <p>{{$login_failed_message}}</p>
                        @endif
                    </div>

                    @if(isset($success_message))
                        <p class="text-success" style="color: darkgreen; font-family: Arial;">{{$success_message}}</p>
                    @endif

                    <p> Fill the form with your login information.</p>
                    <div class="form-group col-xs-12 floating-label-form-group controls @if ($errors->has('email')) has-error @endif">
                        <label>Email Address</label>
                        <input type="email" name="email" value="{{Input::get('email')}}" class="form-control" placeholder="Email Address" id="email" required data-validation-required-message="Please enter your email address.">
                        {{--{{ Form::email('email', '', array('class'=>'form-control', 'placeholder'=>'Email Address')) }}--}}
                        @if ($errors->has('email')) <p class="help-block text-danger">{{ $errors->first('email') }} </p> @endif
                    </div>
                </div>
                <div class="row control-group">
                    <div class="form-group col-xs-12 floating-label-form-group controls @if ($errors->has('email')) has-error @endif">
                        <label>Password</label>
                        <input type="password" rows="5" name="password" class="form-control" placeholder="Password" id="message" required data-validation-required-message="Please enter a password."/>
                        @if ($errors->has('password')) <p class="help-block text-danger">{{ $errors->first('password') }}</p> @endif

                    </div>
                </div>
                <br>
                <div id="success"></div>
                <div class="row">
                    <div class="form-group col-xs-12">
                        <button type="submit" class="btn btn-success btn-lg" name="login" value="login">Submit</button>
                    </div>
                </div>
            {{Form::close()}}

        </div>

        <div class="col-md-4 col-md-offset-1">

            {{ Form::open(array( 'route' =>array('user.postAuth'))) }}
            <div class="row control-group">
                <p> Not yet registered! Please register as an User.</p>
            </div>
            <br>
            <div id="success"></div>
            <div class="row">
                <div class="form-group col-xs-12">
                    <button type="submit" class="btn btn-success btn-lg" name="register" value="register">Register</button>
                </div>
            </div>
            {{Form::close()}}

        </div>


    </div>


@stop

app/views/users/user_registration.blade.php
/**
* Created by PhpStorm.
* User: MahabubAkram
* Date: 1/18/2015
* Time: 3:47 PM
*/

@extends('layouts.product')
@section('main')


    <!-- start: Create Product Form -->
    <h2 style="font-size:2em;">User Information</h2>
    <hr>
    <div class="help-block text-danger">
        @if($errors->count() > 0)
            <p>The following errors have occurred:</p>

            <ul>
                @foreach($errors->all() as $message)
                    <li>{{$message}}</li>
                @endforeach
            </ul>
        @endif
    </div>


    <div class="row">
        <div class="col-lg-6 col-lg-offset-1">
            {{ Form::open(array( 'route' =>array('user.register'), 'method' => 'POST')) }}
            <h2 style="font-size:1em; margin-bottom: 2%; color:#463C54;">Name Input Section</h2>
            <div class="row control-group @if ($errors->has('firstname')) has-error @endif">
                <div class="form-group col-xs-10 floating-label-form-group controls">
                    <label style="color: red">*</label>
                    <label>First Name</label>
                    <input type="text" name="firstname"  value="{{Input::get('firstname')}}" class="form-control" placeholder="First Name" id="firstname" required data-validation-required-message="Please enter your first name.">
                    @if ($errors->has('firstname')) <p class="help-block text-danger">{{ $errors->first('firstname') }}</p> @endif
                </div>
            </div>
            <div class="row control-group @if ($errors->has('lastname')) has-error @endif">
                <div class="form-group col-xs-10 floating-label-form-group controls">
                    <label style="color: red">*</label>
                    <label>Last Name</label>
                    <input type="text" name="lastname" value="{{Input::get('lastname')}}" class="form-control" placeholder="Last Name" id="lastname" required data-validation-required-message="Please enter your last name.">
                    @if ($errors->has('lastname')) <p class="help-block text-danger">{{ $errors->first('lastname') }}</p> @endif
                </div>
            </div>

            <h2 style="font-size:1em; margin-top: 5%; margin-bottom:2%; color:#463C54;">Email Input Section</h2>
            <div class="row control-group @if ($errors->has('email')) has-error @endif">
                <div class="form-group col-xs-10 floating-label-form-group controls">
                    <label style="color: red">*</label>
                    <label>Email Address</label>
                    <input type="email" name="email" value="{{Input::get('email')}}" class="form-control" placeholder="Email Address" id="email" required data-validation-required-message="Please enter your email address.">
                    @if ($errors->has('email')) <p class="help-block text-danger">{{ $errors->first('email') }}</p> @endif
                </div>
            </div>

            <div class="row control-group @if ($errors->has('email_confirmation')) has-error @endif">
                <div class="form-group col-xs-10 floating-label-form-group controls">
                    <label style="color: red">*</label>
                    <label>Confirm Email Address</label>
                    <input type="email" name="email_confirmation" value="{{Input::get('email_confirmation')}}" class="form-control" placeholder="Confirm Email Address" id="email" required data-validation-required-message="Please enter the same email address.">
                    @if ($errors->has('email_confirmation')) <p class="help-block text-danger">{{ $errors->first('email_confirmation') }}</p> @endif
                </div>
            </div>

            <h2 style="font-size:1em; margin-top: 5%; margin-bottom:2%; color:#463C54;">Password Input Section</h2>
            <div class="row control-group @if ($errors->has('password')) has-error @endif">
                <div class="form-group col-xs-10 floating-label-form-group controls">
                    <label style="color: red">*</label>
                    <label>Password</label>
                    <input type="password" name="password" class="form-control" placeholder="Password" id="password" required data-validation-required-message="Please enter your password.">
                    @if ($errors->has('password')) <p class="help-block text-danger">{{ $errors->first('password') }}</p> @endif
                </div>
            </div>

            <div class="row control-group @if ($errors->has('password_confirmation')) has-error @endif">
                <div class="form-group col-xs-10 floating-label-form-group controls">
                    <label style="color: red">*</label>
                    <label>Confirm Password</label>
                    <input type="password" name="password_confirmation" class="form-control" placeholder="Confirm Password" id="password" required data-validation-required-message="Please enter the same password again.">
                    @if ($errors->has('password_confirmation')) <p class="help-block text-danger">{{ $errors->first('password_confirmation') }}</p> @endif
                </div>
            </div>

            <h2 style="font-size:1em; margin-top: 5%; margin-bottom:2%; color:#463C54;">Optional Input Section</h2>
            <div class="row control-group">
                <div class="form-group col-xs-10 floating-label-form-group controls">
                    <label>Phone</label>
                    <input type="text" name="phone" value="{{Input::get('phone')}}" class="form-control" placeholder="+880......" id="phone">
                    <p class="help-block text-danger"></p>
                </div>
            </div>

            <div class="row control-group">
                <div class="form-group col-xs-10 floating-label-form-group controls">
                    <label>Cell Phone</label>
                    <input type="text" name="cell_phone" value="{{ Input::get('cell_phone') }}" class="form-control" placeholder="+880......" id="cell_phone">
                    <p class="help-block text-danger"></p>
                </div>
            </div>


            <div id="success"></div>
            <div class="row" style="margin-top: 5%;">
                <div class="form-group col-xs-12" style="font-size: 1em;">
                    <button type="submit" style="font-size: 1.5em;" class="fa fa-sign-in btn btn-success btn-group-sm"> Sign Up</button>
                </div>
            </div>
            {{Form::close()}}

        </div>
    </div>


@stop

app/views/users/user_settings.blade.php
/**
* Created by PhpStorm.
* User: MahabubAkram
* Date: 1/18/2015
* Time: 3:47 PM
*/

@extends('layouts.product')
@section('main')


    <!-- start: Create Product Form -->
    <h2 style="font-size:1.5em;">Vendor Information</h2>
    <hr>
    <div class="row">
        <div class="col-lg-6 col-lg-offset-2">
            {{ Form::open(array( 'route' =>array('user.login'), 'method' => 'POST')) }}
            <div class="row control-group">
                <div class="form-group col-xs-10 floating-label-form-group controls">
                    <label>*Vendor First Name</label>
                    <input type="text" name="firstname" value="{{$user_data->firstname}}" class="form-control" placeholder="Name of the product" id="email" required data-validation-required-message="Please enter your email address." readonly>
                    {{--{{ Form::email('email', '', array('class'=>'form-control', 'placeholder'=>'Email Address')) }}--}}
                    <p class="help-block text-danger"></p>
                </div>
            </div>

            <div class="row control-group">
                <div class="form-group col-xs-10 floating-label-form-group controls">
                    <label>*Vendor Last Name</label>
                    <input type="text" name="lastname" value="{{$user_data->lastname}}" class="form-control" placeholder="Name of the product" id="email" required data-validation-required-message="Please enter your email address." readonly>
                    {{--{{ Form::email('email', '', array('class'=>'form-control', 'placeholder'=>'Email Address')) }}--}}
                    <p class="help-block text-danger"></p>
                </div>
            </div>

            <div class="row control-group">
                <div class="form-group col-xs-4 floating-label-form-group controls">
                    <label>*Status</label>
                    <select name="category" class="form-control" disabled>
                        <option value="one" @if ($user_data->status == 2) selected has-error @endif>Active</option>
                        <option value="two" @if ($user_data->status == 1) selected has-error @endif>Hidden</option>
                        <option value="three" @if ($user_data->status == 0) selected has-error @endif>Disable</option>
                    </select>
                    <p class="help-block text-danger"></p>
                </div>
            </div>
        </div>
    </div>


    <h2 style="font-size:1.5em;">Contact Information</h2>
    <hr>
    <div class="row">
        <div class="col-lg-6 col-lg-offset-2">
            {{ Form::open(array( 'route' =>array('user.login'), 'method' => 'POST')) }}
            <div class="row control-group">
                <div class="form-group col-xs-10 floating-label-form-group controls">
                    <label>Email</label>
                    <input type="email" name="email" value="{{$user_data->email}}" class="form-control" placeholder="Name of the product" id="email" required data-validation-required-message="Please enter your email address.">
                    {{--{{ Form::email('email', '', array('class'=>'form-control', 'placeholder'=>'Email Address')) }}--}}
                    <p class="help-block text-danger"></p>
                </div>
            </div>
            <div class="row control-group">
                <div class="form-group col-xs-10 floating-label-form-group controls">
                    <label>Phone</label>
                    <input type="text" name="phone" value="{{$user_data->phone}}" class="form-control" placeholder="Name of the product" id="email" required data-validation-required-message="Please enter your email address.">
                    {{--{{ Form::email('email', '', array('class'=>'form-control', 'placeholder'=>'Email Address')) }}--}}
                    <p class="help-block text-danger"></p>
                </div>
            </div>
            <div class="row control-group">
                <div class="form-group col-xs-10 floating-label-form-group controls">
                    <label>Mobile</label>
                    <input type="text" name="cell_phone" value="{{$user_data->cell_phone}}" class="form-control" placeholder="Name of the product" id="email" required data-validation-required-message="Please enter your email address.">
                    {{--{{ Form::email('email', '', array('class'=>'form-control', 'placeholder'=>'Email Address')) }}--}}
                    <p class="help-block text-danger"></p>
                </div>
            </div>
        </div>
    </div>

    <h2 style="font-size:1.5em;">Shipping Information</h2>
    <hr>
    <div class="row">
        <div class="col-lg-6 col-lg-offset-2">
            {{ Form::open(array( 'route' =>array('user.login'), 'method' => 'POST')) }}
            <div class="row control-group">
                <div class="form-group col-xs-10 floating-label-form-group controls">
                    <label>Address</label>
                    <input type="email" name="email" class="form-control" placeholder="Name of the product" id="email" required data-validation-required-message="Please enter your email address.">
                    {{--{{ Form::email('email', '', array('class'=>'form-control', 'placeholder'=>'Email Address')) }}--}}
                    <p class="help-block text-danger"></p>
                </div>
            </div>
            <div class="row control-group">
                <div class="form-group col-xs-10 floating-label-form-group controls">
                    <label>City</label>
                    <input type="email" name="email" class="form-control" placeholder="Name of the product" id="email" required data-validation-required-message="Please enter your email address.">
                    {{--{{ Form::email('email', '', array('class'=>'form-control', 'placeholder'=>'Email Address')) }}--}}
                    <p class="help-block text-danger"></p>
                </div>
            </div>
            <div class="row control-group">
                <div class="form-group col-xs-10 floating-label-form-group controls">
                    <label>Post Code</label>
                    <input type="email" name="email" class="form-control" placeholder="Name of the product" id="email" required data-validation-required-message="Please enter your email address.">
                    {{--{{ Form::email('email', '', array('class'=>'form-control', 'placeholder'=>'Email Address')) }}--}}
                    <p class="help-block text-danger"></p>
                </div>
            </div>
            <div class="row">
                <div class="form-group col-xs-10" style="font-size: 1em;">
                    <button type="submit" style="font-size: 1.5em; float: right" class="fa fa-plus btn btn-success btn-lg"> Submit</button>
                </div>
            </div>
            {{Form::close()}}
        </div>
    </div>

@stop